### ISSUE TITLE
Component action

### ISSUE THREAD

**Issue by JLou** [AxaFrance/design-system#3]

**Comment by adrien-dos** [comment]
Actual version : https://axafrance.github.io/react-toolkit/latest/storybook/?path=/story/components-action--link

Design versions : 
white : https://6ssje8.axshare.com/?id=k2icad&p=icone_header___blanc&g=1 

![image](https://github.com/AxaFrance/design-system/assets/154349821/5bf8f25a-1d32-41e7-a566-4c0b75417c91)

This component must only  be used on header.

**circle :** 
Width : 24px
Height : 24px
background-color : #00008F

**icon :** 
Must be selected from google material library
height : 12px
width : auto
