### ISSUE TITLE
Component Alert

### ISSUE THREAD

**Issue by JLou** [AxaFrance/design-system#4]
Exposed the alert component from @axa-fr/react-toolkit

https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-alert--alert-story

**Comment by adrien-dos** [comment]
### Success

Actual version : https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-alert--alert-story&args=classModifier:success

Design version : https://6ssje8.axshare.com/?id=s45o5o&p=message___succes

**Left side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/ec598056-7b1e-403e-add2-17c21a562718)

background-color : **#0C7D3B**

icon material : **check circle**
width : **20px**
height : **20px**
color : **white**

**Right side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/daf3b2ce-c2fe-4738-84ae-1cf3f04fed42)

background-color : **#FAFFFB**
border : **1px solid ##85B398**

Title : 
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Bold**
color : **#0C7D3B**
line-height : **20px** 

Description :
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Regular**
color : **#0C7D3B**
line-height : **20px** 

**With bullet points :** 
Space between title and list must be 12px 
![image](https://github.com/AxaFrance/design-system/assets/154349821/170678d5-5336-4fd4-b2f8-0ce13094eea4)


**With close :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/c8e4a22d-991a-45a3-aa73-fe718b5d2b04)

icon material : **close**
width : **14px**
height : **14px**
color : **#0C7D3B**

**Comment by adrien-dos** [comment]
### Information

Actual version : https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-alert--alert-story&args=classModifier:info

Design version : https://6ssje8.axshare.com/?id=rtze02&p=message___info

**Left side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/78278587-643f-45da-b283-22b13533be8a)
background-color : **#3871b5**

icon material : **info**
width : **20px**
height : **20px**
color : **white**

**Right side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/bd7fadb6-b31c-4ec0-b4ae-d8ef51906e2a)

background-color : **#f5fbfd**
border : **1px solid #9cb8da**

Title : 
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Bold**
color : **#3871b5**
line-height : **20px**

Description :
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Regular**
color : **#3871b5**
line-height : **20px**

**With bullet points :** 
Space between title and list must be **12px**
![image](https://github.com/AxaFrance/design-system/assets/154349821/87531b29-b9fe-4663-8c04-1a3b1dfaf864)


**With close :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/51d982e2-3e07-4fa4-b057-2210c80f0ab9)

icon material : **close**
width : **14px**
height : **14px**
color : **#3871b5**

**Comment by adrien-dos** [comment]
### Danger

Actual version : https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-alert--alert-story

Design version : https://6ssje8.axshare.com/?id=ccetvh&p=message___alerte&g=5

**Left side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/496b38fc-e5f3-4a27-8a5c-814ebe3eaf1d)

background-color : **#BC4C2D**

icon material : **warning**
width : **20px**
height : **20px**
color : **white**

**Right side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/209698fd-777a-4007-9fd0-6e4a150c3154)

background-color : **#FFF1EF**
border : **1px solid #DEA696**

Title : 
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Bold**
color : **#BC4C2D**
line-height : **20px**

Description :
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Regular**
color : **#BC4C2D**
line-height : **20px**

**With bullet points :** 
Space between title and list must be **12px**
![image](https://github.com/AxaFrance/design-system/assets/154349821/25a874a2-7f2b-4685-8029-ca942e83bc6c)


**With close :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/8b1a2dde-395c-460c-ae56-a0ef9e61555a)

icon material : **close**
width : **14px**
height : **14px**
color : **#BC4C2D**

**Comment by adrien-dos** [comment]
### Error

Actual version : https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-alert--alert-story&args=classModifier:error

Design version : https://6ssje8.axshare.com/?id=oqfczq&p=message___erreur&g=5

**Left side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/28827448-c342-4b71-b5c7-a9d168ab9900)

background-color : **#C7102E**

icon material : **error**
width : **20px**
height : **20px**
color : **white**

**Right side :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/73a217f9-4635-4487-81bc-394a0f25e2ec)

background-color : **#FFFAFB**
border : **1px solid #D38693**

Title : 
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Bold**
color : **#C7102E**
line-height : **20px**

Description :
Font-family : **Source sans pro**
font-size : **16px**
font-weight : **Regular**
color : **#C7102E**
line-height : **20px**

**With bullet points :**
Space between title and list must be 12px
![image](https://github.com/AxaFrance/design-system/assets/154349821/d55abf05-05f2-4508-971d-8ce2adb8fcea)


**With close :** 
![image](https://github.com/AxaFrance/design-system/assets/154349821/2f996283-bc26-4774-a933-0716fa760b22)

icon material : **close**
width : **14px**
height : **14px**
color : **#C7102E**
