### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by MartinWeb** [AxaFrance/design-system#43]
Add dependabot in the project

**Comment by MartinWeb** [comment]
![image](https://github.com/AxaFrance/design-system/assets/1991349/333165f9-0721-4c1b-a569-517ce144af79)

**Comment by SebastienDegodez** [comment]
A voir si renovatebot ne serait pas interressant pour s'aligner sur ce que nous avons ailleurs.

De plus, il a déjà ete validé par nos instances.

https://github.com/apps/renovate

**Comment by MartinWeb** [comment]
> A voir si renovatebot ne serait pas interressant pour s'aligner sur ce que nous avons ailleurs.
> 
> De plus, il a déjà ete validé par nos instances.
> 
> https://github.com/apps/renovate

@SebastienDegodez on s'est dit qu'on partait sur dependabot car directement intégré a github donc ça semble plus simple. C'est aussi ce que l'on avait sur le projet react-toolkit
